# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    facts:        'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision:    
      repo:       git://github.com/enterprisemodules/provision.git
      branch:     docker_run_opts
  forge_modules:
    easy_type:              enterprisemodules-easy_type
    partition:              enterprisemodules-partition
    ora_install:            enterprisemodules-ora_install
    ora_config:             enterprisemodules-ora_config
    ora_cis:                enterprisemodules-ora_cis
    pwshlib:                puppetlabs/pwshlib
    powershell:             puppetlabs/powershell
    stdlib:                 puppetlabs/stdlib
    echo:                   ipcrm/echo
    archive:                puppet/archive
    augeas_core:            puppetlabs-augeas_core
    augeasproviders_core:   herculesteam-augeasproviders_core
    augeasproviders_sysctl: herculesteam-augeasproviders_sysctl
    limits:                 saz/limits
    firewall:               puppetlabs-firewall
    firewalld:              puppet-firewalld
