# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    ora_profile: "#{source_dir}"
  repositories:
    facts:                  https://github.com/puppetlabs/puppetlabs-facts.git
    puppet_agent:           https://github.com/puppetlabs/puppetlabs-puppet_agent.git
    provision:              https://github.com/puppetlabs/provision.git
    easy_type:              https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/enterprisemodules/easy_type_src.git
    ora_install:            https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/enterprisemodules/ora_install.git
    ora_config:             https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/enterprisemodules/ora_config.git
    ora_secured:            https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/enterprisemodules/ora_secured.git
  forge_modules:
    partition:              enterprisemodules-partition
    powershell:             puppetlabs/powershell
    pwshlib:                puppetlabs/pwshlib
    stdlib:                 puppetlabs/stdlib
    echo:                   ipcrm/echo
    archive:                puppet/archive
    augeas_core:            puppetlabs-augeas_core
    augeasproviders_core:   puppet-augeasproviders_core
    augeasproviders_grub:   puppet-augeasproviders_grub
    augeasproviders_sysctl: puppet-augeasproviders_sysctl
    limits:                 saz/limits
    firewall:               puppetlabs-firewall
    firewalld:              puppet-firewalld
    systemd:                puppet-systemd
