RSpec.configure do |c|
  c.mock_with :rspec
end

# The Forge release of enterprisemodules-ora_install (pinned in .fixtures.yml)
# is missing the ora_install::opatch defined type, which db_patches.pp depends
# on. Drop a minimal stub into the fixture after spec_prep has run so the
# catalog-compile specs work without a Forge bump. The file is recreated each
# run because spec_prep wipes the fixture directory.
opatch_stub = File.expand_path('fixtures/modules/ora_install/manifests/opatch.pp', __dir__)
if File.directory?(File.dirname(opatch_stub)) && !File.exist?(opatch_stub)
  File.write(opatch_stub, <<~PUPPET)
    # Test-only stub of ora_install::opatch (autogenerated by spec_helper).
    define ora_install::opatch (
      $ensure                  = present,
      $oracle_product_home_dir = undef,
      $patch_id                = undef,
      $tmp_dir                 = undef,
      $schedule                = undef,
      $source                  = undef,
      $sub_patches             = undef,
      $provider                = undef,
      $tag                     = undef,
    ) {}
  PUPPET
end

# FacterDB ships RHEL 10 and OracleLinux 10 only for Facter 5.x; Puppet 8
# bundles Facter 4.x, so on_supported_os silently skips those OS contexts.
# Point rspec-puppet-facts at our locally-generated fact fixtures so the
# 10-major releases declared in metadata.json actually get exercised.
ENV['FACTERDB_SEARCH_PATHS'] = File.expand_path('fixtures/facter', __dir__)

# macOS libc crypt(3) only supports DES, so puppetlabs-stdlib's pw_hash
# raises "system does not support enhanced salts" when asked for SHA-256
# or SHA-512. Polyfill String#crypt via the pure-Ruby unix_crypt gem so
# catalog-compile specs work on Darwin.
if RUBY_PLATFORM =~ /darwin/ && 'a'.crypt('$6$abc$') !~ /^\$6\$/
  require 'unix_crypt'
  class String
    alias_method :_libc_crypt, :crypt unless method_defined?(:_libc_crypt)
    def crypt(salt)
      case salt
      when /\A\$6\$([^$]*)\$?/ then UnixCrypt::SHA512.build(self, Regexp.last_match(1))
      when /\A\$5\$([^$]*)\$?/ then UnixCrypt::SHA256.build(self, Regexp.last_match(1))
      when /\A\$1\$([^$]*)\$?/ then UnixCrypt::MD5.build(self, Regexp.last_match(1))
      else _libc_crypt(salt)
      end
    end
  end
end

require 'puppetlabs_spec_helper/module_spec_helper'
require 'rspec-puppet-facts'
require 'puppet-catalog_rspec'
# rubocop: disable Style/MixinUsage
include RspecPuppetFacts
# rubocop: enable Style/MixinUsage

default_facts = {
  :puppetversion => Puppet.version,
  :facterversion => Facter.version
}

default_facts_path = File.expand_path(File.join(File.dirname(__FILE__), 'default_facts.yml'))
default_module_facts_path = File.expand_path(File.join(File.dirname(__FILE__), 'default_module_facts.yml'))

default_facts.merge!(YAML.safe_load(File.read(default_facts_path))) if File.exist?(default_facts_path) && File.readable?(default_facts_path)

default_facts.merge!(YAML.safe_load(File.read(default_module_facts_path))) if File.exist?(default_module_facts_path) && File.readable?(default_module_facts_path)
require_relative 'support/unit/shared_examples'

RSpec.configure do |c|
  c.default_facts = default_facts
  c.hiera_config = File.expand_path(File.join(__FILE__, '../fixtures/hiera.yaml'))
  # c.before(:each) do
  #   Puppet::Util::Log.level = :debug
  #   Puppet::Util::Log.newdestination(:console)
  # end
end
