HOSTS:
  ora.example.com:
    roles:
      - master
      - agent
    platform: el-7-x86_64
    hypervisor : docker
    image: centos:7
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'yum remove puppet-agent puppet5-release -y'  # The rpm is still there, but the files not
    mount_folders:
      software:
        host_path: software
        container_path: /software
CONFIG:
  type: aio
  log_level: debug
  # log_level: info
ssh:
  password: root
  # auth_methods: ["password"]
